#web:
#  build: .
#  command: /run.sh
#  links:
#   - statsd
#   - grafana
#  ports:
#   - "80:80"

statsd:
  image: shakr/statsd-influxdb
  ports:
    - "8125:8125/udp"
  env_file:
    - env.statsd
  links:
    - influxdb

influxdb:
  image: tutum/influxdb:0.9
  expose:
    - "8090"
    - "8099"
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  volumes:
    - /data/influxdb:/data  
  env_file:
    - 'env.influxdb'

grafana:
  image: grafana/grafana:4.0.2
  ports:
    - "3000:3000"
  volumes:
    - /data/grafana:/var/lib/grafana
  links:
    - statsd  
    - influxdb

